config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "tasks", to: "tasks#index"

  get "tasks/new", to: "tasks#new" 
  post "tasks", to: "tasks#create"

  get "tasks/:id", to: "tasks#show", as: :task

  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch "tasks/:id", to: "tasks#update"

  delete "tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path(@tasks)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container">
  <h1>Update Task</h1>
  <%= form_for(@task) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control'%>

    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>

    <%= f.label :completed %>
    <%= f.check_box :completed %>

    <%= f.submit class: 'btn btn-primary', id: 'updated_task' %>
  <% end %>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <h1>Tasks List</h1>
   <% @tasks.each do |task| %>
    <div>
      <% if task.completed == false %>
        <i class="far fa-square">
      <% else %>
        <i class="far fa-check-square"></i>
      <% end %>
      </i> <%= link_to task.title, task_path(task) %> 
      <%= link_to task_path(task),
        method: :delete, 
        data: { confirm: "Are You Fucking Sure?" } do %>
        <i class="far fa-trash-alt"></i>
      <% end %>
    </div>
  <% end %>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control'%>

  <%= f.label :details %>
  <%= f.text_field :details, class: 'form-control' %>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/show.html.erb
<div class="container">
  <h1><%= @task.title%></h1>

  <h3><%= @task.details %></h3>

  <%= link_to "Edit", edit_task_path, class: 'btn btn-primary' %>

  <%= link_to "Back to list", tasks_path, class: 'btn btn-primary' %>
</div>